// import React from 'react';
// // import '../globals.css';
// import Header from "../components/header";
// import Footer from "../components/footer";


// function Layout({ children }) {
//   return (
//     <main className='p-0 m-0 h-full w-full sm:text-lg lg:text-2xl 2xl:text-3xl'>
//       <Header />
//       {children}
//       <Footer />
//     </main>
//   );
// }


import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',

}

export default function RootLayout({ children }) {

  return (
    <html lang='fr'>
      <body>{children}</body>
    </html>
  );
};